development:
  adapter: postgresql
  encoding: utf8
  database: project_development
  pool: 5
  username: mohammed
  password: password

production:
  adapter: postgresql
  encoding: utf8
  database: bookapi
  pool: 5
  username: db_user
  password: 

