# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 167f64c53a10f4d359cbfffa8563756aa677d315285427fe97905ab9024f94e2fe92afd4b341033784cdf1a058b1923cb79ef1b1d5cf28404ede4f1f2e080019

test:
  secret_key_base: 8f3a2fcbdf74a58c9dd81008bc1d7f10f32a4a3ecbab67d0f99e87eda8ec04f449ac386971d2dfdbfd86f93dd190fbee1587394a32822cd95044dc6c8e858d68

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
